###
GET http://localhost:2023/api/course-service/v1/course/get/321987321?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
DELETE  http://localhost:2023/api/course-service/v1/course/delete/51900753253221?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
DELETE  http://localhost:2023/api/course-service/v1/course/delete/51900753253221/force?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
PUT  http://localhost:2023/api/course-service/v1/course/restore/519007932222?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
GET http://localhost:2023/api/course-service/v1/course/get-all?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
GET http://localhost:2023/api/course-service/v1/course/get-all-deleted?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
POST http://localhost:2023/api/course-service/v1/course/new?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "code": 38485322,
    "name":"Subject C",
    "credits": 12,
    "description": "This is a description of the subject C",
    "prerequisite": [],
    "departmentAllowed": "213298731"
}


# ==============================================================================================================


###
GET http://localhost:2023/api/course-service/v1/semester/get/HK1-2023-2024?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
DELETE  http://localhost:2023/api/course-service/v1/semester/delete/HK1-2023-2024?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
DELETE  http://localhost:2023/api/course-service/v1/semester/delete/HK1-2023-2024/force?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
PUT  http://localhost:2023/api/course-service/v1/semester/restore/HK1-2023-2024?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
GET http://localhost:2023/api/course-service/v1/semester/get-all?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
GET http://localhost:2023/api/course-service/v1/semester/get-all-deleted?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
POST http://localhost:2023/api/course-service/v1/semester/new?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "alias": "HK2-2023-2024"
}


# ==============================================================================================================

###
GET  http://localhost:2023/api/course-service/v1/academic/get?studentId=19065533&semesterAlias=HK1-2023-2024&api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json
###
GET  http://localhost:2023/api/course-service/v1/academic/statistics/HK1-2023-2024?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

###
POST http://localhost:2023/api/course-service/v1/academic/new?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "studentId":"19602432",
    "courseCode":2023001,
    "semesterAlias":"HK1-2023-2024"
}

# ==============================================================================================================

###
POST  http://localhost:2023/api/course-service/v1/schedule/new?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "courseCode":38485322,
    "semesterAlias":"HK1-2023-2024",
    "groupId":1,
    "limit": 2,
    "periods":[1,2,3],
    "weeks":[1,2,3],
    "day":"Tuesday"
}

###
POST  http://localhost:2023/api/course-service/v1/schedule/all?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "semesterAlias":"HK1-2023-2024"
}
###
POST  http://localhost:2023/api/course-service/v1/schedule/enroll?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "studentId":"19602432",
    "courseCode":2023001,
    "semesterAlias":"HK1-2023-2024",
    "groupId":1
}
###
POST  http://localhost:2023/api/course-service/v1/schedule/enrollment/all?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "studentId":"19602432"
}
###
POST  http://localhost:2023/api/course-service/v1/schedule/enrollment/semester?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "studentId":"19065533",
    "semesterAlias": "HK1-2023-2024"
}
